const product = {
 id: 7136647282771,
 title: 'AI Designed Custom Decal',
 handle: 'ai-designed-custom-decal',
 description: '',
 published_at: '2024-01-19T11:03:32-05:00',
 created_at: '2024-01-19T11:03:17-05:00',
 vendor: 'squirrels-and-squirrels',
 type: '',
 tags: [],
 price: 1099,
 price_min: 1099,
 price_max: 16000,
 available: true,
 price_varies: true,
 compare_at_price: null,
 compare_at_price_min: 0,
 compare_at_price_max: 0,
 compare_at_price_varies: false,
 variants: [
  {
   id: 41462479290451,
   title: 'Decal 3"',
   option1: 'Decal 3"',
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: 'AI Designed Custom Decal - Decal 3"',
   public_title: 'Decal 3"',
   options: ['Decal 3"'],
   price: 1099,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462479323219,
   title: 'Digital Print',
   option1: 'Digital Print',
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: 'AI Designed Custom Decal - Digital Print',
   public_title: 'Digital Print',
   options: ['Digital Print'],
   price: 1149,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490234963,
   title: 'Decal 5"',
   option1: 'Decal 5"',
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: 'AI Designed Custom Decal - Decal 5"',
   public_title: 'Decal 5"',
   options: ['Decal 5"'],
   price: 1249,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490267731,
   title: 'Decal 6"',
   option1: 'Decal 6"',
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: 'AI Designed Custom Decal - Decal 6"',
   public_title: 'Decal 6"',
   options: ['Decal 6"'],
   price: 1449,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490300499,
   title: 'Decal 7"',
   option1: 'Decal 7"',
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: 'AI Designed Custom Decal - Decal 7"',
   public_title: 'Decal 7"',
   options: ['Decal 7"'],
   price: 1549,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490333267,
   title: 'Decal 8"',
   option1: 'Decal 8"',
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: 'AI Designed Custom Decal - Decal 8"',
   public_title: 'Decal 8"',
   options: ['Decal 8"'],
   price: 1649,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490366035,
   title: 'Decal 10"',
   option1: 'Decal 10"',
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: 'AI Designed Custom Decal - Decal 10"',
   public_title: 'Decal 10"',
   options: ['Decal 10"'],
   price: 1849,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490398803,
   title: 'Decal 12"',
   option1: 'Decal 12"',
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: 'AI Designed Custom Decal - Decal 12"',
   public_title: 'Decal 12"',
   options: ['Decal 12"'],
   price: 2049,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490431571,
   title: 'Decal 15"',
   option1: 'Decal 15"',
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: 'AI Designed Custom Decal - Decal 15"',
   public_title: 'Decal 15"',
   options: ['Decal 15"'],
   price: 2349,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490464339,
   title: 'Decal 18"',
   option1: 'Decal 18"',
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: 'AI Designed Custom Decal - Decal 18"',
   public_title: 'Decal 18"',
   options: ['Decal 18"'],
   price: 2999,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490497107,
   title: 'Print 11"x14" Vertical',
   option1: 'Print 11"x14" Vertical',
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: 'AI Designed Custom Decal - Print 11"x14" Vertical',
   public_title: 'Print 11"x14" Vertical',
   options: ['Print 11"x14" Vertical'],
   price: 2000,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490529875,
   title: 'Print 11"x14" Horiz',
   option1: 'Print 11"x14" Horiz',
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: 'AI Designed Custom Decal - Print 11"x14" Horiz',
   public_title: 'Print 11"x14" Horiz',
   options: ['Print 11"x14" Horiz'],
   price: 2000,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490562643,
   title: 'Print 16"x20" Vertical',
   option1: 'Print 16"x20" Vertical',
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: 'AI Designed Custom Decal - Print 16"x20" Vertical',
   public_title: 'Print 16"x20" Vertical',
   options: ['Print 16"x20" Vertical'],
   price: 2400,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490595411,
   title: 'Print 16"x20" Horiz',
   option1: 'Print 16"x20" Horiz',
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: 'AI Designed Custom Decal - Print 16"x20" Horiz',
   public_title: 'Print 16"x20" Horiz',
   options: ['Print 16"x20" Horiz'],
   price: 2400,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490628179,
   title: 'Print 18"x24" Vertical',
   option1: 'Print 18"x24" Vertical',
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: 'AI Designed Custom Decal - Print 18"x24" Vertical',
   public_title: 'Print 18"x24" Vertical',
   options: ['Print 18"x24" Vertical'],
   price: 2800,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490660947,
   title: 'Print 18"x24" Horiz',
   option1: 'Print 18"x24" Horiz',
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: 'AI Designed Custom Decal - Print 18"x24" Horiz',
   public_title: 'Print 18"x24" Horiz',
   options: ['Print 18"x24" Horiz'],
   price: 2800,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490693715,
   title: 'Print 24"x36" Vertical',
   option1: 'Print 24"x36" Vertical',
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: 'AI Designed Custom Decal - Print 24"x36" Vertical',
   public_title: 'Print 24"x36" Vertical',
   options: ['Print 24"x36" Vertical'],
   price: 3200,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490726483,
   title: 'Print 24"x36" Horiz',
   option1: 'Print 24"x36" Horiz',
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: 'AI Designed Custom Decal - Print 24"x36" Horiz',
   public_title: 'Print 24"x36" Horiz',
   options: ['Print 24"x36" Horiz'],
   price: 3200,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490759251,
   title: "Banner 2'x4'",
   option1: "Banner 2'x4'",
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: "AI Designed Custom Decal - Banner 2'x4'",
   public_title: "Banner 2'x4'",
   options: ["Banner 2'x4'"],
   price: 8000,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490792019,
   title: "Banner 2'x5'",
   option1: "Banner 2'x5'",
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: "AI Designed Custom Decal - Banner 2'x5'",
   public_title: "Banner 2'x5'",
   options: ["Banner 2'x5'"],
   price: 8500,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490824787,
   title: "Banner 2'x6'",
   option1: "Banner 2'x6'",
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: "AI Designed Custom Decal - Banner 2'x6'",
   public_title: "Banner 2'x6'",
   options: ["Banner 2'x6'"],
   price: 9000,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490857555,
   title: "Banner 2'x8'",
   option1: "Banner 2'x8'",
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: "AI Designed Custom Decal - Banner 2'x8'",
   public_title: "Banner 2'x8'",
   options: ["Banner 2'x8'"],
   price: 9500,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490890323,
   title: "Banner 3'x4'",
   option1: "Banner 3'x4'",
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: "AI Designed Custom Decal - Banner 3'x4'",
   public_title: "Banner 3'x4'",
   options: ["Banner 3'x4'"],
   price: 9000,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490923091,
   title: "Banner 3'x5'",
   option1: "Banner 3'x5'",
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: "AI Designed Custom Decal - Banner 3'x5'",
   public_title: "Banner 3'x5'",
   options: ["Banner 3'x5'"],
   price: 9500,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490955859,
   title: "Banner 3'x6'",
   option1: "Banner 3'x6'",
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: "AI Designed Custom Decal - Banner 3'x6'",
   public_title: "Banner 3'x6'",
   options: ["Banner 3'x6'"],
   price: 10000,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462490988627,
   title: "Banner 3'x8'",
   option1: "Banner 3'x8'",
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: "AI Designed Custom Decal - Banner 3'x8'",
   public_title: "Banner 3'x8'",
   options: ["Banner 3'x8'"],
   price: 10500,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462491021395,
   title: "Banner 3'x10'",
   option1: "Banner 3'x10'",
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: "AI Designed Custom Decal - Banner 3'x10'",
   public_title: "Banner 3'x10'",
   options: ["Banner 3'x10'"],
   price: 11500,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462491054163,
   title: "Banner 3'x12'",
   option1: "Banner 3'x12'",
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: "AI Designed Custom Decal - Banner 3'x12'",
   public_title: "Banner 3'x12'",
   options: ["Banner 3'x12'"],
   price: 12500,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462491086931,
   title: "Banner 4'x4'",
   option1: "Banner 4'x4'",
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: "AI Designed Custom Decal - Banner 4'x4'",
   public_title: "Banner 4'x4'",
   options: ["Banner 4'x4'"],
   price: 12000,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462491119699,
   title: "Banner 4'x5'",
   option1: "Banner 4'x5'",
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: "AI Designed Custom Decal - Banner 4'x5'",
   public_title: "Banner 4'x5'",
   options: ["Banner 4'x5'"],
   price: 12500,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462491152467,
   title: "Banner 4'x6'",
   option1: "Banner 4'x6'",
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: "AI Designed Custom Decal - Banner 4'x6'",
   public_title: "Banner 4'x6'",
   options: ["Banner 4'x6'"],
   price: 13000,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462491185235,
   title: "Banner 4'x8'",
   option1: "Banner 4'x8'",
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: "AI Designed Custom Decal - Banner 4'x8'",
   public_title: "Banner 4'x8'",
   options: ["Banner 4'x8'"],
   price: 14000,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462491218003,
   title: "Banner 4'x10'",
   option1: "Banner 4'x10'",
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: "AI Designed Custom Decal - Banner 4'x10'",
   public_title: "Banner 4'x10'",
   options: ["Banner 4'x10'"],
   price: 16000,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
  {
   id: 41462491250771,
   title: "Banner 4'x12'",
   option1: "Banner 4'x12'",
   option2: null,
   option3: null,
   sku: '',
   requires_shipping: true,
   taxable: true,
   featured_image: null,
   available: true,
   name: "AI Designed Custom Decal - Banner 4'x12'",
   public_title: "Banner 4'x12'",
   options: ["Banner 4'x12'"],
   price: 1500,
   weight: 0,
   compare_at_price: null,
   inventory_management: null,
   barcode: '',
   quantity_rule: {
    min: 1,
    max: null,
    increment: 1,
   },
   quantity_price_breaks: [],
   requires_selling_plan: false,
   selling_plan_allocations: [],
  },
 ],
 images: [],
 featured_image: null,
 options: [
  {
   name: 'Shape',
   position: 1,
   values: [
    'Decal 3"',
    'Digital Print',
    'Decal 5"',
    'Decal 6"',
    'Decal 7"',
    'Decal 8"',
    'Decal 10"',
    'Decal 12"',
    'Decal 15"',
    'Decal 18"',
    'Print 11"x14" Vertical',
    'Print 11"x14" Horiz',
    'Print 16"x20" Vertical',
    'Print 16"x20" Horiz',
    'Print 18"x24" Vertical',
    'Print 18"x24" Horiz',
    'Print 24"x36" Vertical',
    'Print 24"x36" Horiz',
    "Banner 2'x4'",
    "Banner 2'x5'",
    "Banner 2'x6'",
    "Banner 2'x8'",
    "Banner 3'x4'",
    "Banner 3'x5'",
    "Banner 3'x6'",
    "Banner 3'x8'",
    "Banner 3'x10'",
    "Banner 3'x12'",
    "Banner 4'x4'",
    "Banner 4'x5'",
    "Banner 4'x6'",
    "Banner 4'x8'",
    "Banner 4'x10'",
    "Banner 4'x12'",
   ],
  },
 ],
 url: '/products/ai-designed-custom-decal',
 requires_selling_plan: false,
 selling_plan_groups: [],
}
