# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "mj-devel"
client_id = "6f3fda83af52960ed0312ab35af379f8"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[app_proxy]
url = "https://home.ink-dev.com/"
subpath = "image"
prefix = "a"

[pos]
embedded = false

[build]
dev_store_url = "squirrels-and-squirrels.myshopify.com"
