export const products = [
  { id: 'decal', label: 'Decal', isSelect: false, options: [] },
  { id: 'truck', label: 'Truck Back Window Graphics', isSelect: false, options: [] },
  {
    id: 'digital',
    label: 'Digital Print',
    isSelect: true,
    options: [
      { id: 'dp1', label: '11x14 Vertical', ar: '4:5' },
      { id: 'dp2', label: '11x14 Horizontal', ar: '5:4' },
      { id: 'dp3', label: '16x20 Vertical', ar: '4:5' },
      { id: 'dp4', label: '16x20 Horizontal', ar: '5:4' },
      { id: 'dp5', label: '18x24 Vertical', ar: '3:4' },
      { id: 'dp6', label: '18x24 Horizontal', ar: '4:3' },
      { id: 'dp7', label: '24x36 Vertical', ar: '2:3' },
      { id: 'dp8', label: '24x36 Horizontal', ar: '3:2' },
    ],
  },
  { id: 'tshirt', label: 'T-Shirt', isSelect: true, options: [{ id: 'ts1', label: 'Coming Soon' }] },
  { id: '3d', label: '3D Printed Model', isSelect: true, options: [{ id: '3d1', label: 'Coming Soon' }] },
  {
    id: 'banner',
    label: 'Banner',
    isSelect: true,
    options: [
      { id: 'b1', label: `2'x4"`, ar: '2:1' },
      { id: 'b2', label: `2'x5"`, ar: '5:2' },
      { id: 'b3', label: `2'x6"`, ar: '3:1' },
      { id: 'b4', label: `2'x8"`, ar: '4:1' },
      { id: 'b5', label: `3'x4"`, ar: '4x3' },
      { id: 'b6', label: `3'x5"`, ar: '5x3' },
      { id: 'b7', label: `3'x6"`, ar: '2x1' },
      { id: 'b8', label: `3'x8" (Most Common)`, ar: '8x3' },
      { id: 'b9', label: `3'x10"`, ar: '10x3' },
      { id: 'b10', label: `3'x12"`, ar: '4x1' },
      { id: 'b11', label: `4'x4"`, ar: '1x1' },
      { id: 'b12', label: `4'x5"`, ar: '5x4' },
      { id: 'b13', label: `4'x6"`, ar: '3x2' },
      { id: 'b14', label: `4'x8"`, ar: '2x1' },
      { id: 'b15', label: `4'x10"`, ar: '5x2' },
      { id: 'b16', label: `4'x12"`, ar: '3x1' },
    ],
  },
]
